package report

import (
	"strings"
	"testing"
	"time"

	"github.com/Ashfaaq98/ocsf-console-ir/internal/store"
)

func at(s string) time.Time {
	t, err := time.Parse("2006-01-02 15:04", s)
	if err != nil {
		panic(err)
	}
	return t
}

// full is a case with something in every section.
func full() CaseReport {
	return CaseReport{
		Case: store.Case{
			ID: "c1", Title: "Suspected account compromise — m.chen",
			Severity: "high", Status: "investigating", AssignedTo: "ashfaaq",
			CreatedAt: at("2026-08-08 03:12"),
		},
		Briefing: store.Briefing{
			Statement:  "An account authenticated from two countries nine minutes apart.",
			Hypotheses: []store.Hypothesis{{Text: "Session token theft", Confidence: "likely"}},
			NextActions: []store.NextAction{
				{Text: "Revoke sessions", Done: true},
				{Text: "Check mailbox rules", Done: false},
			},
		},
		Findings: []store.Finding{
			{Title: "Confirmed C2 beaconing", Severity: "high", RiskScore: 91,
				StatusID: 2, Verdict: "True Positive", FirstSeen: at("2026-08-08 03:14"),
				Desc: "Eight outbound sessions at a fifteen-minute interval."},
			{Title: "Impossible travel sign-in", Severity: "medium", RiskScore: 55,
				FirstSeen: at("2026-08-08 03:12")},
		},
		Events: []store.Event{
			{Message: "Outbound to 45.147.230.11", Timestamp: at("2026-08-08 03:15")},
		},
		Notes: []store.Note{
			{Content: "Blocked 45.147.230.11 at the firewall", Author: "ashfaaq",
				CreatedAt: at("2026-08-08 03:52")},
			{Content: "not a decision", LinkedType: store.NoteTypeStatement,
				CreatedAt: at("2026-08-08 03:00")},
		},
		Audit: []store.AuditEntry{
			{Action: "create_case", Actor: "ashfaaq", Timestamp: at("2026-08-08 03:20")},
		},
		Indicators: []store.CaseIndicator{
			{Type: "IP Address", TypeID: 2, Value: "45.147.230.11", Source: "asserted",
				Sightings: 6, FirstSeen: at("2026-08-07 01:05"), LastSeen: at("2026-08-08 11:40")},
		},
		Version:   "v0.2.0",
		Generated: at("2026-08-10 12:40"),
	}
}

// The report carries every part of the case an analyst is asked about.
func TestAReportCoversTheCase(t *testing.T) {
	got := full().Markdown()

	for _, want := range []string{
		"# Suspected account compromise — m.chen",
		"**Severity** HIGH", "**Status** investigating",
		"**Opened** 2026-08-08 03:12",
		"An account authenticated from two countries",
		"Session token theft",
		"- [x] Revoke sessions",
		"- [ ] Check mailbox rules",
		"Confirmed C2 beaconing",
		"Eight outbound sessions",
		"45.147.230.11",
		"Blocked 45.147.230.11 at the firewall",
		"Generated by Console-IR v0.2.0",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("the report is missing %q", want)
		}
	}
}

// The same inputs give the same document, so what was sent can be checked.
func TestAReportIsDeterministic(t *testing.T) {
	if full().Markdown() != full().Markdown() {
		t.Error("two renderings of one case differ")
	}
}

// The timeline is one account in order, not four lists.
func TestTheTimelineReadsForward(t *testing.T) {
	got := full().Markdown()
	section := got[strings.Index(got, "## Timeline"):]
	section = section[:strings.Index(section, "## Indicators")]

	var stamps []string
	for _, line := range strings.Split(section, "\n") {
		if i := strings.Index(line, "`"); i >= 0 {
			if j := strings.Index(line[i+1:], "`"); j > 0 {
				stamps = append(stamps, line[i+1:i+1+j])
			}
		}
	}
	if len(stamps) < 4 {
		t.Fatalf("the timeline holds %d entries, want the finding, event, note and activity:\n%s",
			len(stamps), section)
	}
	for i := 1; i < len(stamps); i++ {
		if stamps[i] < stamps[i-1] {
			t.Errorf("the timeline runs backwards at %q after %q", stamps[i], stamps[i-1])
		}
	}
	// Briefing notes belong to the summary, not the narrative.
	if strings.Contains(section, "not a decision") {
		t.Error("a briefing note leaked into the timeline")
	}
}

// A generated summary is labelled as generated. Handing a client a model's
// paragraph as the investigator's account is the one thing a report must not do.
func TestAGeneratedSummaryIsLabelled(t *testing.T) {
	r := full()
	r.Briefing.HasSummary = true
	r.Briefing.Summary = "The account was likely compromised."
	r.Briefing.SummaryAt = at("2026-08-09 10:00")

	got := r.Markdown()
	if !strings.Contains(got, "Generated summary") || !strings.Contains(got, "language model") {
		t.Errorf("the generated summary is not marked as generated:\n%s", got)
	}
}

// An empty case still produces a readable document that says what is missing.
func TestAnEmptyCaseStillReports(t *testing.T) {
	got := CaseReport{
		Case:      store.Case{ID: "c2", Title: "Nothing yet"},
		Version:   "v0.2.0",
		Generated: at("2026-08-10 12:40"),
	}.Markdown()

	for _, want := range []string{
		"# Nothing yet",
		"_No incident statement was recorded._",
		"_No findings are attached to this case._",
		"_No notes were recorded._",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("an empty case's report is missing %q:\n%s", want, got)
		}
	}
}

// A value containing a pipe must not shift every column after it.
func TestPipesDoNotBreakTables(t *testing.T) {
	r := full()
	r.Indicators[0].Value = `powershell -enc AAA | out-file x`
	got := r.Markdown()

	if !strings.Contains(got, `\| out-file`) {
		t.Errorf("a pipe in an indicator value was not escaped:\n%s", got)
	}
}
